### ISSUE TITLE
add legend should be changed to refresh legend

### ISSUE THREAD

**Issue by yihangx** [cytoscape/legend-creator#12]
The Remove Legends button removes all legends, but the Add legend button adds unlimited legends, and some of them overlap with each other.
"Add legend" button should be changed to "refresh legend"
![Screenshot 2020-12-07 182635](https://user-images.githubusercontent.com/46608109/101430427-d2b34000-38b9-11eb-862e-4b62541cb7f4.png)

**Comment by khanspers** [comment]
This is done.
